font-dir = local_fonts
papersize = A4
size = 9.2x6.05
no-page-footer = true
tab-side = left-alternate
tabheight = 0.77
tabwidth = 5
#black-tabs
#log-level = DEBUG
expansion = dominion2ndEdition
outfile = output/dom2nd-v7.pdf